theme: minima
title: Sit, Stand, Rock, and Roll
author: Ross Wilkinson
email: ross.wilkinson@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a collection of all my thoughts on the biomechanics of cycling.

# social links
twitter_username: rd_wilkinson # DO NOT include the @ character, or else the build will fail!
github_username:  ross-wilkinson # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
